### ISSUE TITLE
List of only recipes with clickable expand action

### ISSUE THREAD

**Issue by ivlovric** [kaelspencer/MMM-PaprikaMenu#23]
Hi and thanks for this nice plugin!
I am building kitchen recipe portal with touchscreen monitor and wondering if this plugin can be extended to add list of recipes that can be opened by clicking?

Thanks a lot,
I

**Comment by kaelspencer** [comment]
Interesting idea. All the data needed is available via the Parpika APIs, so that isn't an issue. Right now it's just a list.

Are you thinking that you'd touch a recipe, then the plugin would update it's layout to show the recipe itself? Or take you somewhere else?

**Comment by ivlovric** [comment]
Yes, I was thinking when touching or clicking on recipe that plugin would update its layout to show recipe itself and to conveniently go back to list of recipes afterwards

**Comment by kaelspencer** [comment]
I think this is a reasonable add. I personally wouldn't use it because I don't have it displayed on a touch screen, but it sure would be handy to have the whole recipe available to view.

Is this something you're interested in implementing?

**Comment by ivlovric** [comment]
Thanks for your assessment @kaelspencer 

I can try to do something about it but without any promises. If its ok with you, It seems easiest for me and to have more freedom is to fork this project with focus on recipes with credits to you and this project?

**Comment by kaelspencer** [comment]
Yep, do whatever works best for you. Please let me know how it goes. :)

**Comment by ivlovric** [comment]
Its done with special thanks 😊 
https://github.com/ivlovric/MMM-MagicReplicator

**Comment by kaelspencer** [comment]
This looks great @ivlovric ! I'm looking forward to trying it out.
