### ISSUE TITLE
Limit the number of past days being displayed

### ISSUE THREAD

**Issue by iwaldrum** [kaelspencer/MMM-PaprikaMenu#4]
Love the module.. Is there a way we could limit the number of past days to be displayed? This would help in the amount of space the module takes up.

**Comment by kaelspencer** [comment]
Yeah, that seems reasonable. I'll add an option _showPriorEntries_ which will default to true. If set to false, past days of the week will be hidden. I'm thinking an int option like _priorEntryLimit_ with a valid range of [0, 6] for cases where maybe you want to only see the previous day. Setting to 6 would give the current behavior (show all previous days in this current week).

Would that satisfy what you're looking for?

**Comment by iwaldrum** [comment]
That would be perfect.. thanks!

**Comment by kaelspencer** [comment]
Decided to go with two options: a way to limit previous days and a way to limit the total number of previous menu items.
