### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by jgrossrieder** [kaelspencer/MMM-PaprikaMenu#9]
Hi,

I've a paprika account and I'm trying to setup this on my  mirror.
My configuration is the following:

```
                {
                        module: "MMM-PaprikaMenu",
                        header: "Menus",
                        position: "top_right",
                        config: {
                                email: "aaaaaaaaaa",
                                password: "bbbbbbbbb",
                                weekStartsOnSunday: false,
                                roundPictureCorners: true,
                                snackDisplay: "Snack",
                                breakfastDisplay: "Pti déj",
                                lunchDisplay: "Dîner",
                                dinnerDisplay: "Souper",
                                dateFormat:"dddd"
                        }
                },
```

I also did the npm install after having cloned the module.

But when I display it, I see:
![image](https://user-images.githubusercontent.com/7582002/78385377-07108700-75dc-11ea-9204-d37cd8bd2ab5.png)

No errors, nothing. Any idea how I can troubleshot this or what the issue could be?

**Comment by kaelspencer** [comment]
Can you share some logs? The relevant entries should start with `MMM-PaprikaMenu`.

**Comment by jgrossrieder** [comment]
> Can you share some logs? The relevant entries should start with `MMM-PaprikaMenu`.

I think you can close this, I just rebooted my raspberry and now it's working. Didn't know reboot was required
